name: turnos-pro

services:
- name: frontend
  github:
    repo: ericfrick132/beauty-salon
    branch: master
    deploy_on_push: true
  source_dir: src/frontend
  dockerfile_path: src/frontend/Dockerfile.prod
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
    preserve_path_prefix: true
  envs:
  - key: REACT_APP_API_URL
    value: "https://turnos-pro.com/api"
  - key: REACT_APP_APP_NAME
    value: "TurnosPro"

- name: api
  github:
    repo: ericfrick132/beauty-salon
    branch: master
    deploy_on_push: true
  source_dir: src/backend/BookingPro.API
  dockerfile_path: src/backend/BookingPro.API/Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
    preserve_path_prefix: true
  health_check:
    http_path: /health
    timeout_seconds: 10
    interval_seconds: 30
  envs:
  - key: ASPNETCORE_ENVIRONMENT
    value: "Production"
  - key: ASPNETCORE_URLS
    value: "http://+:8080"
  - key: DATABASE_URL
    value: "${db.DATABASE_URL}"
  - key: ConnectionStrings__DefaultConnection
    value: "${db.DATABASE_URL}"
  - key: Jwt__Key
    value: "${JWT_KEY}"
    type: SECRET
  - key: FrontendUrl
    value: "https://turnos-pro.com"
  - key: EnableSwaggerInProduction
    value: "true"
  - key: SEED_DATA
    value: "true"
  - key: BackendUrl
    value: "https://turnos-pro.com"
  - key: MercadoPago__ClientId
    value: "${MERCADOPAGO_CLIENT_ID}"
    type: SECRET
  - key: MercadoPago__ClientSecret
    value: "${MERCADOPAGO_CLIENT_SECRET}"
    type: SECRET
  - key: MercadoPago__AccessToken
    value: "${MERCADOPAGO_ACCESS_TOKEN}"
    type: SECRET
  - key: MercadoPago__RedirectUri
    value: "https://turnos-pro.com/api/mercadopago/callback"
  - key: MercadoPago__WebhookUrl
    value: "https://turnos-pro.com/api/webhooks/mercadopago"

databases:
- name: db
  engine: PG
  version: "16"
  size: db-s-dev-database
  num_nodes: 1