export const brand = {
  brand_name: 'TurnosPro',
  brand_domain: 'https://turnos-pro.com',
  marketing_path: '/turnos',
  lang: 'es-AR',
  primary_keyword: 'reservas con seña y recordatorios automáticos',
  secondary_keywords: ['señas con MercadoPago', 'recordatorios por WhatsApp', 'agenda online 24/7', 'software de turnos', 'menos no-shows'],
  city_country_variants: ['Argentina', 'Buenos Aires', 'LatAm'],
  og_image: '/og-cover.jpg',
  logo_url: '/logo.png',
  support_email: 'soporte@turnos-pro.com',
  support_phone: '+54 11 1234-5678',
  demo_booking_url: 'mailto:soporte@turnos-pro.com?subject=Quiero%20una%20demo%20de%20TurnosPro',
  demo_video_url: 'https://www.loom.com/embed/6c2b52a60e9d4c1d8fae6e60d5b3b111',
} as const;
