export const brand = {
  brand_name: 'TurnosPro',
  brand_domain: 'https://turnos-pro.com',
  marketing_path: '/turnos',
  lang: 'es-AR',
  primary_keyword: 'reservas con seña y recordatorios automáticos',
  secondary_keywords: ['señas con MercadoPago', 'recordatorios por WhatsApp', 'agenda online 24/7', 'software de turnos', 'menos ausencias'],
  city_country_variants: ['Argentina', 'Buenos Aires', 'LatAm'],
  og_image: '/og-cover.jpg',
  logo_url: '/logo.png',
  support_email: 'hola@gymhero.com',
  support_phone: '+1 689 256 4251',
  demo_booking_url: 'https://wa.me/16892564251?text=Hola!%20Quiero%20una%20demo%20de%20TurnosPro',
  demo_video_url: 'https://www.loom.com/embed/6c2b52a60e9d4c1d8fae6e60d5b3b111',
  instagram_url: 'https://www.instagram.com/turnospro',
  whatsapp_url: 'https://wa.me/16892564251',
  linkedin_url: 'https://www.linkedin.com/company/efcloud',
} as const;
